version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
  - master
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: >-
    nuget restore

    . "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\sn.exe" -k ./ImageSharpCompare/ImageSharpCompare.snk
build:
  project: ImageSharpCompare.sln
  publish_aspnet_core: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}-prerelease'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

artifacts:
- path: '**\ImageSharpCompare.*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r